#!/bin/bash -eu

NAME=`cat pom.xml | grep '<name>' | head -1 | sed 's_.*<name>\([^<]*\)</name>.*_\1_'`
VERSION=`cat pom.xml | grep '<version>' | head -1 | sed 's_.*<version>\([^<]*\)</version>.*_\1_'`

DIST=dist
pushd `dirname $0` >/dev/null; BASE=`pwd`; popd >/dev/null
TAR=$BASE/$NAME-$VERSION.tar.gz

echo "Building $NAME-$VERSION"
echo

mvn clean package

echo
echo "Creating $TAR"

shopt -s nullglob

mkdir -p $DIST/lib
cp -u target/$NAME-$VERSION.jar $DIST/lib/

shopt -u nullglob

(
  cd $DIST
  rm -f $TAR
  tar czf $TAR *
  tar tf $TAR | sed -r 's/^/  /'
)
